var dir_8171cbf35320adbbdeacc57a241055d4 =
[
    [ "memchr.c", "memchr_8c.html", "memchr_8c" ],
    [ "memcmp.c", "memcmp_8c.html", "memcmp_8c" ],
    [ "memcpy.c", "memcpy_8c.html", "memcpy_8c" ],
    [ "memmove.c", "memmove_8c.html", "memmove_8c" ],
    [ "memset.c", "memset_8c.html", "memset_8c" ],
    [ "strcat.c", "strcat_8c.html", "strcat_8c" ],
    [ "strchr.c", "strchr_8c.html", "strchr_8c" ],
    [ "strcmp.c", "strcmp_8c.html", "strcmp_8c" ],
    [ "strcoll.c", "strcoll_8c.html", "strcoll_8c" ],
    [ "strcpy.c", "strcpy_8c.html", "strcpy_8c" ],
    [ "strcspn.c", "strcspn_8c.html", "strcspn_8c" ],
    [ "strerror.c", "strerror_8c.html", "strerror_8c" ],
    [ "strlen.c", "strlen_8c.html", "strlen_8c" ],
    [ "strncat.c", "strncat_8c.html", "strncat_8c" ],
    [ "strncmp.c", "strncmp_8c.html", "strncmp_8c" ],
    [ "strncpy.c", "strncpy_8c.html", "strncpy_8c" ],
    [ "strpbrk.c", "strpbrk_8c.html", "strpbrk_8c" ],
    [ "strrchr.c", "strrchr_8c.html", "strrchr_8c" ],
    [ "strspn.c", "strspn_8c.html", "strspn_8c" ],
    [ "strstr.c", "strstr_8c.html", "strstr_8c" ],
    [ "strtok.c", "strtok_8c.html", "strtok_8c" ],
    [ "strxfrm.c", "strxfrm_8c.html", "strxfrm_8c" ]
];