var dir_bd09fe9b8da6c5f4ff0d9ee0689299b7 =
[
    [ "filesystem_calls.c", "filesystem__calls_8c.html", "filesystem__calls_8c" ],
    [ "filesystem_calls.h", "filesystem__calls_8h.html", "filesystem__calls_8h" ],
    [ "generic_vga.c", "generic__vga_8c.html", "generic__vga_8c" ],
    [ "generic_vga.h", "generic__vga_8h.html", "generic__vga_8h" ],
    [ "heap_calls.c", "heap__calls_8c.html", "heap__calls_8c" ],
    [ "heap_calls.h", "heap__calls_8h.html", "heap__calls_8h" ],
    [ "keyboard_calls.c", "keyboard__calls_8c.html", "keyboard__calls_8c" ],
    [ "keyboard_calls.h", "keyboard__calls_8h.html", "keyboard__calls_8h" ],
    [ "memory_calls.c", "memory__calls_8c.html", "memory__calls_8c" ],
    [ "memory_calls.h", "memory__calls_8h.html", "memory__calls_8h" ],
    [ "partitions_calls.c", "partitions__calls_8c.html", "partitions__calls_8c" ],
    [ "partitions_calls.h", "partitions__calls_8h.html", "partitions__calls_8h" ],
    [ "pc_speaker_calls.c", "pc__speaker__calls_8c.html", "pc__speaker__calls_8c" ],
    [ "pc_speaker_calls.h", "pc__speaker__calls_8h.html", "pc__speaker__calls_8h" ],
    [ "power_calls.c", "power__calls_8c.html", "power__calls_8c" ],
    [ "power_calls.h", "power__calls_8h.html", "power__calls_8h" ],
    [ "process_calls.c", "process__calls_8c.html", "process__calls_8c" ],
    [ "process_calls.h", "process__calls_8h.html", "process__calls_8h" ],
    [ "rtc_calls.c", "rtc__calls_8c.html", "rtc__calls_8c" ],
    [ "rtc_calls.h", "rtc__calls_8h.html", "rtc__calls_8h" ],
    [ "serial_calls.c", "serial__calls_8c.html", "serial__calls_8c" ],
    [ "serial_calls.h", "serial__calls_8h.html", "serial__calls_8h" ],
    [ "terminal_calls.c", "terminal__calls_8c.html", "terminal__calls_8c" ],
    [ "terminal_calls.h", "terminal__calls_8h.html", "terminal__calls_8h" ],
    [ "time_calls.c", "time__calls_8c.html", "time__calls_8c" ],
    [ "time_calls.h", "time__calls_8h.html", "time__calls_8h" ]
];