var dir_b4522d0cc015c126b1fc705c1b7d9036 =
[
    [ "micros_console.c", "micros__console_8c.html", "micros__console_8c" ],
    [ "micros_console.h", "micros__console_8h.html", "micros__console_8h" ],
    [ "micros_filesystem.c", "micros__filesystem_8c.html", "micros__filesystem_8c" ],
    [ "micros_filesystem.h", "micros__filesystem_8h.html", "micros__filesystem_8h" ],
    [ "micros_generic_vga.c", "micros__generic__vga_8c.html", "micros__generic__vga_8c" ],
    [ "micros_generic_vga.h", "micros__generic__vga_8h.html", "micros__generic__vga_8h" ],
    [ "micros_heap.c", "micros__heap_8c.html", "micros__heap_8c" ],
    [ "micros_heap.h", "micros__heap_8h.html", "micros__heap_8h" ],
    [ "micros_interrupts.c", "micros__interrupts_8c.html", "micros__interrupts_8c" ],
    [ "micros_interrupts.h", "micros__interrupts_8h.html", "micros__interrupts_8h" ],
    [ "micros_keyboard.c", "micros__keyboard_8c.html", "micros__keyboard_8c" ],
    [ "micros_keyboard.h", "micros__keyboard_8h.html", "micros__keyboard_8h" ],
    [ "micros_memory.c", "micros__memory_8c.html", "micros__memory_8c" ],
    [ "micros_memory.h", "micros__memory_8h.html", "micros__memory_8h" ],
    [ "micros_partitions.c", "micros__partitions_8c.html", "micros__partitions_8c" ],
    [ "micros_partitions.h", "micros__partitions_8h.html", "micros__partitions_8h" ],
    [ "micros_pc_speaker.c", "micros__pc__speaker_8c.html", "micros__pc__speaker_8c" ],
    [ "micros_pc_speaker.h", "micros__pc__speaker_8h.html", "micros__pc__speaker_8h" ],
    [ "micros_power.c", "micros__power_8c.html", "micros__power_8c" ],
    [ "micros_power.h", "micros__power_8h.html", "micros__power_8h" ],
    [ "micros_process.c", "micros__process_8c.html", "micros__process_8c" ],
    [ "micros_process.h", "micros__process_8h.html", "micros__process_8h" ],
    [ "micros_rtc.c", "micros__rtc_8c.html", "micros__rtc_8c" ],
    [ "micros_rtc.h", "micros__rtc_8h.html", "micros__rtc_8h" ],
    [ "micros_serial.c", "micros__serial_8c.html", "micros__serial_8c" ],
    [ "micros_serial.h", "micros__serial_8h.html", "micros__serial_8h" ],
    [ "micros_timer.c", "micros__timer_8c.html", "micros__timer_8c" ],
    [ "micros_timer.h", "micros__timer_8h.html", "micros__timer_8h" ]
];