var dir_379c9d5c7c2794d598f49cf370249a22 =
[
    [ "arithmetic_operations.c", "arithmetic__operations_8c.html", "arithmetic__operations_8c" ],
    [ "arithmetic_operations.h", "arithmetic__operations_8h.html", "arithmetic__operations_8h" ],
    [ "ascii_adjustments_operations.c", "ascii__adjustments__operations_8c.html", "ascii__adjustments__operations_8c" ],
    [ "ascii_adjustments_operations.h", "ascii__adjustments__operations_8h.html", "ascii__adjustments__operations_8h" ],
    [ "bit_operations.c", "bit__operations_8c.html", "bit__operations_8c" ],
    [ "bit_operations.h", "bit__operations_8h.html", "bit__operations_8h" ],
    [ "exchange_operations.c", "exchange__operations_8c.html", "exchange__operations_8c" ],
    [ "exchange_operations.h", "exchange__operations_8h.html", "exchange__operations_8h" ],
    [ "internal_funcs.c", "internal__funcs_8c.html", null ],
    [ "internal_funcs.h", "internal__funcs_8h.html", "internal__funcs_8h" ],
    [ "io_operations.c", "io__operations_8c.html", "io__operations_8c" ],
    [ "io_operations.h", "io__operations_8h.html", "io__operations_8h" ],
    [ "jump_operations.c", "jump__operations_8c.html", "jump__operations_8c" ],
    [ "jump_operations.h", "jump__operations_8h.html", "jump__operations_8h" ],
    [ "misc_operations.c", "misc__operations_8c.html", "misc__operations_8c" ],
    [ "misc_operations.h", "misc__operations_8h.html", "misc__operations_8h" ],
    [ "mov_operations.c", "mov__operations_8c.html", "mov__operations_8c" ],
    [ "mov_operations.h", "mov__operations_8h.html", "mov__operations_8h" ],
    [ "opcodes.c", "opcodes_8c.html", "opcodes_8c" ],
    [ "opcodes.h", "opcodes_8h.html", "opcodes_8h" ],
    [ "procedure_operations.c", "procedure__operations_8c.html", "procedure__operations_8c" ],
    [ "procedure_operations.h", "procedure__operations_8h.html", "procedure__operations_8h" ],
    [ "stack_operations.c", "stack__operations_8c.html", "stack__operations_8c" ],
    [ "stack_operations.h", "stack__operations_8h.html", "stack__operations_8h" ],
    [ "string_operations.c", "string__operations_8c.html", "string__operations_8c" ],
    [ "string_operations.h", "string__operations_8h.html", "string__operations_8h" ]
];