FLOPPY_SIZE		= 1440

# generate output image
$(output_image_floppy):
	$(progress) "GENERATE OUTPUT IMAGE"
	$(MKDIR) -p $(@D)
	$(MKFS_DOS) -C $@ $(FLOPPY_SIZE)
	$(MMD) -oi $(output_image_floppy)  $(patsubst $(output_dir)/%, ::%,$(shell find $(output_dir)/ -mindepth 1 -type d))
	$(foreach FILE,\
	$(patsubst $(output_dir)/%, %,$(shell find $(output_dir)/ -mindepth 1 -type f)),\
	$(MCOPY) -oi $(output_image_floppy) $(output_dir)/$(FILE) ::$(FILE); \
	)
